// Generated by scripts/generate_schema.py; source: migrations/0003_v07.sql.
const statements = [
  "CREATE TABLE IF NOT EXISTS study_terms(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,label TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 0,created INTEGER NOT NULL);",
  "CREATE UNIQUE INDEX IF NOT EXISTS active_study_term ON study_terms(user_id) WHERE active=1;",
  "CREATE TABLE IF NOT EXISTS study_archives(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,term_id TEXT NOT NULL,course_id INTEGER NOT NULL,course_name TEXT NOT NULL,device_id TEXT,created INTEGER NOT NULL,UNIQUE(user_id,term_id,course_id));",
  "CREATE TABLE IF NOT EXISTS study_files(id TEXT PRIMARY KEY,archive_id TEXT NOT NULL,source_key TEXT NOT NULL,name TEXT NOT NULL,group_name TEXT NOT NULL,sha TEXT NOT NULL,bytes INTEGER NOT NULL,available INTEGER NOT NULL,updated INTEGER NOT NULL,UNIQUE(archive_id,source_key));",
  "CREATE TABLE IF NOT EXISTS study_notes(id TEXT PRIMARY KEY,archive_id TEXT NOT NULL,source_key TEXT NOT NULL,category TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,url TEXT NOT NULL,section TEXT NOT NULL,partial INTEGER NOT NULL,hash TEXT NOT NULL,updated INTEGER NOT NULL,UNIQUE(archive_id,source_key));",
  "CREATE TABLE IF NOT EXISTS study_note_history(id TEXT PRIMARY KEY,note_id TEXT NOT NULL,body TEXT NOT NULL,title TEXT NOT NULL,hash TEXT NOT NULL,created INTEGER NOT NULL);",
  "CREATE TABLE IF NOT EXISTS job_confirmations(job_id TEXT PRIMARY KEY,dismissed INTEGER NOT NULL DEFAULT 0,confirmed INTEGER NOT NULL DEFAULT 0);",
  "CREATE INDEX IF NOT EXISTS study_archives_owner ON study_archives(user_id);",
  "CREATE INDEX IF NOT EXISTS study_notes_archive ON study_notes(archive_id);",
  "-- Metadata budgets include retained note history. Counters serialize quota checks.\nCREATE TABLE IF NOT EXISTS study_usage(user_id TEXT PRIMARY KEY,chars INTEGER NOT NULL DEFAULT 0);",
  "CREATE TABLE IF NOT EXISTS study_limits(id INTEGER PRIMARY KEY CHECK(id=1),user_chars INTEGER NOT NULL,global_chars INTEGER NOT NULL);",
  "INSERT OR IGNORE INTO study_limits VALUES(1,5000000,100000000);",
  "CREATE TRIGGER IF NOT EXISTS study_usage_limit BEFORE UPDATE ON study_usage BEGIN\n SELECT CASE WHEN NEW.chars > (SELECT user_chars FROM study_limits WHERE id=1) OR\n (SELECT COALESCE(SUM(chars),0) FROM study_usage) - OLD.chars + NEW.chars > (SELECT global_chars FROM study_limits WHERE id=1)\n THEN RAISE(ABORT,'study_text_quota') END;\nEND;",
  "CREATE TRIGGER IF NOT EXISTS study_notes_count_insert AFTER INSERT ON study_notes BEGIN\n INSERT OR IGNORE INTO study_usage(user_id) VALUES((SELECT user_id FROM study_archives WHERE id=NEW.archive_id));\n UPDATE study_usage SET chars=chars+length(NEW.body)+length(NEW.title) WHERE user_id=(SELECT user_id FROM study_archives WHERE id=NEW.archive_id);\nEND;",
  "CREATE TRIGGER IF NOT EXISTS study_note_history_count_insert AFTER INSERT ON study_note_history BEGIN\n INSERT OR IGNORE INTO study_usage(user_id) VALUES((SELECT a.user_id FROM study_archives a JOIN study_notes n ON n.archive_id=a.id WHERE n.id=NEW.note_id));\n UPDATE study_usage SET chars=chars+length(NEW.body)+length(NEW.title) WHERE user_id=(SELECT a.user_id FROM study_archives a JOIN study_notes n ON n.archive_id=a.id WHERE n.id=NEW.note_id);\nEND;",
  "CREATE TRIGGER IF NOT EXISTS study_notes_count_update AFTER UPDATE ON study_notes BEGIN\n UPDATE study_usage SET chars=chars+length(NEW.body)+length(NEW.title)-length(OLD.body)-length(OLD.title) WHERE user_id=(SELECT user_id FROM study_archives WHERE id=NEW.archive_id);\nEND;"
];
const initialized = new WeakMap();
export async function ensureStudySchema(env) {
  if (!initialized.has(env.DB)) {
    const task = (async () => {
      await env.DB.prepare("CREATE TABLE IF NOT EXISTS study_schema(version INTEGER PRIMARY KEY)").run();
      if (await env.DB.prepare("SELECT version FROM study_schema WHERE version=7").first()) return;
      // Only new tables/indexes/triggers. Never rewrite or delete v0.4-v0.6 records.
      await env.DB.batch([...statements.map(sql=>env.DB.prepare(sql)), env.DB.prepare("INSERT OR IGNORE INTO study_schema VALUES(7)")]);
    })();
    initialized.set(env.DB, task);
    task.catch(()=>initialized.delete(env.DB));
  }
  return initialized.get(env.DB);
}
