"""Generate the idempotent Worker bootstrap from the reviewed additive SQL migration."""

import json
import sqlite3
from pathlib import Path

root = Path(__file__).resolve().parent.parent
statements = []
pending = ""
for line in (
    (root / "cloud/migrations/0003_v07.sql").read_text("utf-8").splitlines(True)
):
    pending += line
    if sqlite3.complete_statement(pending):
        statements.append(pending.strip())
        pending = ""
assert not pending.strip()
code = (
    """// Generated by scripts/generate_schema.py; source: migrations/0003_v07.sql.
const statements = """
    + json.dumps(statements, ensure_ascii=False, indent=2)
    + """;
const initialized = new WeakMap();
export async function ensureStudySchema(env) {
  if (!initialized.has(env.DB)) {
    const task = (async () => {
      await env.DB.prepare("CREATE TABLE IF NOT EXISTS study_schema(version INTEGER PRIMARY KEY)").run();
      if (await env.DB.prepare("SELECT version FROM study_schema WHERE version=7").first()) return;
      // Only new tables/indexes/triggers. Never rewrite or delete v0.4-v0.6 records.
      await env.DB.batch([...statements.map(sql=>env.DB.prepare(sql)), env.DB.prepare("INSERT OR IGNORE INTO study_schema VALUES(7)")]);
    })();
    initialized.set(env.DB, task);
    task.catch(()=>initialized.delete(env.DB));
  }
  return initialized.get(env.DB);
}
"""
)
(root / "cloud/src/study_schema.js").write_text(code, "utf-8")
