PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,password TEXT NOT NULL,salt TEXT NOT NULL,created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS pairings(code TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS devices(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),token TEXT NOT NULL UNIQUE,name TEXT NOT NULL,last_seen INTEGER NOT NULL DEFAULT 0,revoked INTEGER NOT NULL DEFAULT 0,snapshot TEXT NOT NULL DEFAULT '{}',schedule_enabled INTEGER NOT NULL DEFAULT 0,schedule_time TEXT NOT NULL DEFAULT '20:00',last_day TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_device ON devices(user_id) WHERE revoked=0;
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),device_id TEXT NOT NULL REFERENCES devices(id),kind TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',created INTEGER NOT NULL,updated INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,lease_until INTEGER NOT NULL DEFAULT 0,lease_token TEXT,result TEXT NOT NULL DEFAULT '{}',request_key TEXT NOT NULL UNIQUE);
CREATE INDEX IF NOT EXISTS job_queue ON jobs(device_id,status,created);
CREATE TABLE IF NOT EXISTS throttles(key TEXT PRIMARY KEY,hits INTEGER NOT NULL,expires INTEGER NOT NULL);
